[package]
name = "tetsu-sys"
description = "cef-rs sys crate"
links = "tetsu"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
doctest = false

[features]
dox = []
sandbox = []

[package.metadata.docs.rs]
features = ["dox"]

[build-dependencies]
anyhow.workspace = true
cmake.workspace = true
fs-err = "3.2.2"
tetsu-download.workspace = true
serde_json.workspace = true
