[package]
name = "tetsu-sys"
description = "Generated bindings to the Chromium Embedded Framework's C API, loading libcef at run time"
links = "tetsu"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
dirs = "6"
libloading.workspace = true

