//! Functions libcef exports, resolved when it is loaded.
//!
//! Rewrites the sys bindings bindgen wrote, which no binary links against. Each `extern "C"` function becomes a `pub unsafe fn` of the same
//! name and signature that calls through `crate::libcef::functions()`, so the
//! safe layer calls it unchanged. A `LibcefFunctions` table of function
//! pointers, resolved by name when the application loads libcef, closes the
//! file. A file already rewritten has no `extern "C"` block left and stays as
//! it is.

use quote::{format_ident, quote};
use std::{ffi::CString, fs, path::Path};

/// The comment bindgen opens its output with, which tokens do not keep.
const HEADER_PREFIX: &str = "/* automatically generated by rust-bindgen";

/// Functions CEF's headers declare that libcef does not export; the C++
/// wrapper's library loader and macOS's `libcef_sandbox.dylib` define them.
/// The rewrite drops them, so loading libcef never looks for them.
const NOT_IN_LIBCEF: [&str; 8] = [
    "cef_load_library",
    "cef_unload_library",
    "cef_scoped_library_loader_create",
    "cef_scoped_library_loader_free",
    "cef_sandbox_initialize",
    "cef_sandbox_destroy",
    "cef_scoped_sandbox_initialize",
    "cef_scoped_sandbox_destroy",
];

/// Rewrites the sys bindings at `source_path`; returns whether anything changed.
pub fn rewrite(source_path: &Path) -> crate::Result<bool> {
    let source = fs::read_to_string(source_path)?;
    let header = source
        .lines()
        .next()
        .filter(|line| line.starts_with(HEADER_PREFIX))
        .map(str::to_owned);
    let file = syn::parse_file(&source)?;

    let mut items = Vec::with_capacity(file.items.len());
    let mut functions = Vec::new();
    for item in file.items {
        match item {
            syn::Item::ForeignMod(foreign) if is_c_abi(&foreign.abi) => {
                for foreign_item in foreign.items {
                    let syn::ForeignItem::Fn(function) = foreign_item else {
                        return Err(crate::Error::Unsupported(
                            "an extern \"C\" item other than a function".into(),
                        ));
                    };
                    if NOT_IN_LIBCEF.contains(&function.sig.ident.to_string().as_str()) {
                        continue;
                    }
                    items.push(wrapper(&function)?);
                    functions.push(function);
                }
            }
            item => items.push(quote!(#item)),
        }
    }

    if functions.is_empty() {
        return Ok(false);
    }

    let table = table(&functions);
    let body = quote! {
        #(#items)*
        #table
    };
    let mut rewritten = String::new();
    if let Some(header) = header {
        rewritten.push_str(&header);
        rewritten.push_str("\n\n");
    }
    rewritten.push_str(&body.to_string());
    fs::write(source_path, rewritten)?;
    crate::parse_tree::format_bindings(source_path)?;

    // Upstream commits some bindings with CRLF; a rewrite keeps the file's
    // line endings so its diff is the rewrite alone
    if source.contains("\r\n") {
        let formatted = fs::read_to_string(source_path)?.replace("\r\n", "\n");
        fs::write(source_path, formatted.replace('\n', "\r\n"))?;
    }

    Ok(true)
}

fn is_c_abi(abi: &syn::Abi) -> bool {
    abi.name.as_ref().is_some_and(|name| name.value() == "C")
}

/// The argument names of `function`, in order.
fn argument_names(function: &syn::ForeignItemFn) -> crate::Result<Vec<syn::Ident>> {
    if function.sig.variadic.is_some() {
        return Err(crate::Error::Unsupported(format!(
            "the variadic function {}",
            function.sig.ident
        )));
    }

    function
        .sig
        .inputs
        .iter()
        .map(|input| match input {
            syn::FnArg::Typed(syn::PatType { pat, .. }) => match pat.as_ref() {
                syn::Pat::Ident(pat) => Ok(pat.ident.clone()),
                _ => Err(crate::Error::Unsupported(format!(
                    "an argument pattern of {}",
                    function.sig.ident
                ))),
            },
            syn::FnArg::Receiver(_) => Err(crate::Error::Unsupported(format!(
                "a receiver on {}",
                function.sig.ident
            ))),
        })
        .collect()
}

/// The function's replacement, calling through the loaded table.
fn wrapper(function: &syn::ForeignItemFn) -> crate::Result<proc_macro2::TokenStream> {
    let attrs = &function.attrs;
    let ident = &function.sig.ident;
    let inputs = &function.sig.inputs;
    let output = &function.sig.output;
    let names = argument_names(function)?;

    Ok(quote! {
        #(#attrs)*
        #[inline]
        pub unsafe fn #ident(#inputs) #output {
            unsafe { (crate::libcef::functions().#ident)(#(#names),*) }
        }
    })
}

/// The table of function pointers and its resolution by name.
fn table(functions: &[syn::ForeignItemFn]) -> proc_macro2::TokenStream {
    let fields = functions.iter().map(|function| {
        let ident = &function.sig.ident;
        let inputs = &function.sig.inputs;
        let output = &function.sig.output;
        quote! { pub #ident: unsafe extern "C" fn(#inputs) #output }
    });
    let resolved = functions.iter().map(|function| {
        let ident = &function.sig.ident;
        let name = CString::new(ident.to_string()).expect("an identifier holds no NUL");
        let name = proc_macro2::Literal::c_string(&name);
        quote! { #ident: unsafe { library.symbol(#name)? } }
    });
    let table = format_ident!("LibcefFunctions");

    quote! {
        #[doc = " The functions libcef exports, resolved when it is loaded."]
        pub struct #table {
            #(#fields,)*
        }

        impl #table {
            pub(crate) fn resolve(
                library: &crate::libcef::Library,
            ) -> Result<Self, crate::libcef::LoadError> {
                Ok(Self {
                    #(#resolved,)*
                })
            }
        }
    }
}
